### ISSUE TITLE
Code donation

### ISSUE THREAD

**Issue by rikkimax** [Yoplitein/vibeirc#1]
Hi, I have some code you might be interested in.
https://bitbucket.org/alphaglosined/civbot/src/8de7097aa132b665303696063fe3536f3903eb59/IRCBot/ircbot/tools/?at=default

Its not complete and at the time when I was working on it I was rewriting some parts to be create/get/is style.
Feel free to use it if you want.

**Comment by Yoplitein** [comment]
I've been perusing the code and most of it looks like stuff I've already implemented. Though there are a few things I will steal, namely the numeric constants and the coloring code. So, thanks!
